In [1]:
import pandas as pd
import os
import json
with open('purchase_data.json') as json_file:  
    data = pd.read_json(json_file)


data_df=pd.DataFrame(data)
data_df.head()

,Age,Gender,Item ID,Item Name,Price,SN
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46
2,34,Male,174,Primitive Blade,2.46,Assastnya25
3,21,Male,92,Final Critic,1.36,Pheusrical25
4,23,Male,63,Stormfury Mace,1.27,Aela59

In [2]:
with open('purchase_data.json') as json_file:  
    data = pd.read_json(json_file)


data_df=pd.DataFrame(data)

#Player Count
NoOfPlayers=(data["SN"].count())
pd.DataFrame([{'Number of Players': NoOfPlayers}])

   Number of Players
0                780

In [11]:
#Purchasing Analysis (Total)

#pd.options.display.float_format = '${:,.2f}'.format

#Calculating Average Purchase Price
AveragePurchasePrice=data_df['Price'].mean()
AvgPrice=round(AveragePurchasePrice,2)

#AveragePurchasePrice

#Calculating total number of purchases
TotalNumberofPurchases=data_df['Item Name'].count()

#Calculating total revenue
TotalRevenue=data_df['Price'].sum()
#TotalRevenue
OutputDisplay=[{'Number Of Unique Items':UniqueItems,'Average Purchase Price':AvgPrice,'Number of Purchases': TotalNumberofPurchases, 'Total Revenue':TotalRevenue}]

pd.DataFrame(OutputDisplay)

,Average Purchase Price,Number Of Unique Items,Number of Purchases,Total Revenue
0,2.93,183,780,"2,286.33"

In [4]:
#Gender Demographics

Gendercal=data_df['Gender'].value_counts()
alepercent1=(Gendercal*100)/data_df['Gender'].count()
GenderDemo1_df=pd.DataFrame({'Percent Of Players':alepercent1,'Total Count':Gendercal})
GenderDemo1_df

                       Percent Of Players  Total Count
Male                            81.153846          633
Female                          17.435897          136
Other / Non-Disclosed            1.410256           11

In [5]:
#Purchasing Analysis (Gender)

grouped_Binned_Gender_df = data_df.groupby("Gender")

Gender_count=grouped_Binned_Gender_df[["Price"]].count()
Avg_Price_Gender=grouped_Binned_Gender_df[["Price"]].mean()
Total_P_Value=grouped_Binned_Gender_df[["Price"]].sum()
Normalized_Totals= Total_P_Value/Gender_count
Gender_count_df=pd.DataFrame(Gender_count)
Gender_count_df
pd.options.display.float_format = '{:,.2f}'.format
Purchasing_Analysis_Gender_df=pd.DataFrame({'Purchase Count':Gender_count["Price"],'Average Purchase Price':Avg_Price_Gender["Price"],'Total Purchase Price':Total_P_Value["Price"],'Normalized Totals':Normalized_Totals["Price"]})
Purchasing_Analysis_Gender_df

,Average Purchase Price,Normalized Totals,Purchase Count,Total Purchase Price
Gender,,,,
Female,2.82,2.82,136,382.91
Male,2.95,2.95,633,"1,867.68"
Other / Non-Disclosed,3.25,3.25,11,35.74

In [6]:
#Age Demographics

bins=[0,10,14,19,24,29,34,39,40]
group_names=['<10','10-14','15-19','20-24','25-29','30-34','35-39','40']
age_demo=pd.cut(data_df['Age'], bins, labels=group_names)
data_df['Binned_Age']=pd.cut(data_df['Age'], bins, labels=group_names)
total_count= data_df['Binned_Age'].value_counts()
binAgepercent1=(total_count*100)/data_df['Age'].count()
binAgepercent1_df=pd.DataFrame({'Percent Of Players':binAgepercent1,'Total Count':total_count,})
binAgepercent1_df

       Percent Of Players  Total Count
20-24               43.08          336
15-19               17.05          133
25-29               16.03          125
30-34                8.21           64
35-39                5.38           42
<10                  4.10           32
10-14                3.97           31
40                   1.79           14

In [7]:
#Purchasing Analysis (Age)

grouped_Binned_Age_df = data_df.groupby("Binned_Age")

P_count=grouped_Binned_Age_df[["Price"]].count()
Avg_Price=grouped_Binned_Age_df[["Price"]].mean()
Total_P_Value=grouped_Binned_Age_df[["Price"]].sum()
        
        #Purchasing_Analysis_df
Normalized_Totals= Total_P_Value/P_count
P_count_df=pd.DataFrame(P_count)
P_count_df
Purchasing_Analysis_df=pd.DataFrame({'Purchase Count':P_count["Price"],'Average Purchase Price':Avg_Price["Price"],'Total Purchase Price':Total_P_Value["Price"],'Normalized Totals':Normalized_Totals["Price"],})
Purchasing_Analysis_df

,Average Purchase Price,Normalized Totals,Purchase Count,Total Purchase Price
Binned_Age,,,,
<10,3.02,3.02,32,96.62
10-14,2.70,2.70,31,83.79
15-19,2.91,2.91,133,386.42
20-24,2.91,2.91,336,978.77
25-29,2.96,2.96,125,370.33
30-34,3.08,3.08,64,197.25
35-39,2.84,2.84,42,119.40
40,3.22,3.22,14,45.11

In [8]:
#Top Spenders

grouped_Binned_Spender_df = data_df.groupby("SN")

Spender_count=grouped_Binned_Spender_df[["Price"]].count()
Avg_Price_Spender=grouped_Binned_Spender_df[["Price"]].mean()
Total_P_Value=grouped_Binned_Spender_df[["Price"]].sum()
Spender_count_df=pd.DataFrame(Spender_count)
Spender_count_df

SP_count_df=pd.DataFrame(Spender_count)
SP_count_df
Spender_Analysis_df=pd.DataFrame({'Purchase Count':Spender_count["Price"],'Average Purchase Price':Avg_Price_Spender["Price"],'Total Purchase Price':Total_P_Value["Price"],})
Spender_Analysis_df

Top_Spenders_df=Spender_Analysis_df.sort_values("Total Purchase Price", ascending=False)
Top_Spenders_df.head()

             Average Purchase Price  Purchase Count  Total Purchase Price
SN
Undirrala66                    3.41               5                 17.06
Saedue76                       3.39               4                 13.56
Mindimnya67                    3.18               4                 12.74
Haellysu29                     4.24               3                 12.73
Eoda93                         3.86               3                 11.58

In [9]:
#Most Popular Items
grouped_Binned_Item_df = data_df.groupby(["Item ID","Item Name"])

Item_count=grouped_Binned_Item_df[["Price"]].count()
Price_Item=grouped_Binned_Item_df[["Price"]].mean()
Total_P_Value=grouped_Binned_Item_df[["Price"]].sum()
Item_count_df=pd.DataFrame(Item_count)
Item_count_df

PopulatItem_count_df=pd.DataFrame(Item_count)
PopulatItem_count_df
PopularItem_Analysis_df=pd.DataFrame({'Purchase Count':Item_count["Price"],'Item Price':Price_Item["Price"],'Total Purchase Price':Total_P_Value["Price"],})
PopularItem_Analysis_df

Most_PopularItem_df=PopularItem_Analysis_df.sort_values(("Total Purchase Price"), ascending=False)
Most_PopularItem_df.head()

,,Item Price,Purchase Count,Total Purchase Price
Item ID,Item Name,,,
34,Retribution Axe,4.14,9,37.26
115,Spectral Diamond Doomblade,4.25,7,29.75
32,Orenmir,4.95,6,29.70
103,Singed Scalpel,4.87,6,29.22
107,"Splitter, Foe Of Subtlety",3.61,8,28.88

In [10]:
#Most Profitable Items

Most_ProfitableItem_df=Most_PopularItem_df["Item Price"]/PopularItem_Analysis_df["Purchase Count"]
Most_ProfitableItem_df.sort_values(ascending=False)

ProfitableItem_Analysis_df=pd.DataFrame({'Purchase Count':Item_count["Price"],'Item Price':Price_Item["Price"],'Total Purchase Price':Total_P_Value["Price"],'Profit Per Unit':Most_ProfitableItem_df})
ProfitableItem_Analysis_df=ProfitableItem_Analysis_df.sort_values('Profit Per Unit', ascending=False)
ProfitableItem_Analysis_df[[ 'Item Price', 'Purchase Count', 'Total Purchase Price']]

,,Item Price,Purchase Count,Total Purchase Price
Item ID,Item Name,,,
147,"Hellreaver, Heirloom of Inception",3.59,1,3.59
2,Verdict,3.40,1,3.40
136,Ghastly Adamantite Protector,3.30,1,3.30
126,Exiled Mithril Longsword,3.25,1,3.25
109,"Downfall, Scalpel Of The Emperor",3.20,1,3.20
28,"Flux, Destroyer of Due Diligence",3.04,1,3.04
168,"Sun Strike, Jaws of Twisted Visions",2.64,1,2.64
96,Blood-Forged Skeletal Spine,4.77,2,9.54
43,Foul Edge,2.38,1,2.38
4,Bloodlord's Fetish,2.28,1,2.28
150,Deathraze,4.54,2,9.08
62,Piece Maker,4.36,2,8.72
56,Foul Titanium Battle Axe,4.33,2,8.66
55,Vindictive Glass Edge,4.26,2,8.52
88,"Emberling, Defender of Delusions",4.10,2,8.20
146,Warped Iron Scimitar,4.08,2,8.16
19,"Pursuit, Cudgel of Necromancy",3.98,2,7.96
132,Persuasion,3.90,2,7.80
164,Exiled Doomblade,1.92,1,1.92
80,Dreamsong,3.81,2,7.62
0,Splinter,1.82,1,1.82
64,Fusion Pummel,3.58,2,7.16
3,Phantomlight,1.79,1,1.79
59,"Lightning, Etcher of the King",1.65,1,1.65
112,Worldbreaker,3.29,2,6.58
42,The Decapitator,4.82,3,14.46
135,Warped Diamond Crusader,4.66,3,13.98
181,Reaper's Toll,4.56,3,13.68
58,"Freak's Bite, Favor of Holy Might",3.03,2,6.06
139,"Mercy, Katana of Dismay",4.37,3,13.11
...,...,...,...,...
85,Malificent Bag,2.17,6,13.02
11,Brimstone,2.52,7,17.64
69,"Frenzy, Defender of the Harvest",1.06,3,3.18
104,Gladiator's Glaive,1.36,4,5.44
86,Stormfury Lantern,1.28,4,5.12
14,Possessed Core,1.59,5,7.95
63,Stormfury Mace,1.27,4,5.08
154,Feral Katana,2.19,7,15.33
44,Bonecarvin Battle Axe,2.46,8,19.68
161,Devine,1.45,5,7.25
10,Sleepwalker,1.73,6,10.38
106,Crying Steel Sickle,2.29,8,18.32
82,Nirvana,1.11,4,4.44
33,Curved Axe,1.35,5,6.75
179,"Wolf, Promise of the Moonwalker",1.88,7,13.16
47,"Alpha, Reach of Ending Hope",1.55,6,9.30
25,Hero Cane,1.03,4,4.12
18,"Torchlight, Bond of Storms",1.77,7,12.39
65,Conqueror Adamantite Mace,1.96,8,15.68
172,Blade of the Grave,1.69,7,11.83
31,Trickster,2.07,9,18.63
123,Twilight's Carver,1.14,5,5.70
130,Alpha,1.56,7,10.92
39,"Betrayal, Whisper of Grieving Widows",2.35,11,25.85
95,Singed Onyx Warscythe,1.03,5,5.15
84,Arcane Gem,2.23,11,24.53
15,Soul Infused Crystal,1.03,6,6.18
92,Final Critic,1.36,8,10.88
13,Serenity,1.49,9,13.41
175,Woeful Adamantite Claymore,1.24,9,11.16